### ISSUE TITLE
Animation styles need to be more specific

### ISSUE THREAD

**Issue by jonbnewman** [footworkjs/footwork#34]
When applying an animation style to a container it is currently using a too-generic animation transition selector of ```all```.

```less
.fw-entity {
  .fade-in {
    opacity: 0;
    .transition(all @fw-animation-speed @fw-animation-easing);
  }
  // ...
}
```

This means applying css like ```:hover``` selectors will also be subject to the animation definition. This has undesirable side effects.
